### PR TITLE
fix: issue #305 mount the component with theme

### LINKED ISSUE #305: Make sure we mount  the components with `theme` and strictly follow the Figma UI design
We found in the component test/sandbox, (xxx.cy.js) there are some component didn't mount the component with the theme, so when we try to integrate the component into the real page, we found the layout of the component changed, e.g. #302 

We should mount the component in this way: 

```
import { mountWithTheme as mount } from '../../models/test-utils';
import Filter from './Filter';

describe('Filter', () => {
  it('Filter', () => {
    cy.viewport(700, 600);
    mount(<Filter />);
  });
});
```

Please go through all the component tests, ends with: `.cy.js`  to make sure all the component is mounted in that way, and make sure the component layout respects the UI design in Figma.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by VWRoli**
# Description

Mount the component with 'theme' in component test files, and fix some design issues as per Figma design file.

Fixes #305 

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] Cypress component tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

File: src/components/VerifiedBadge.js [hunk 1]
```diff
@@ -1,20 +1,15 @@
...
 
 function VerifiedBadge({ verified, badgeName }) {
-  const { classes } = useStyles();
+  const theme = useTheme();
+
   return (
     <Chip
-      className={classes.chip}
-      color={!verified ? 'primary' : 'secondary'}
+      sx={{ borderRadius: theme.spacing(2), marginRight: theme.spacing(2) }}
```
Comment (QuaidBartolomei) [inline src/components/VerifiedBadge.js:11]: `marginRight: theme.spacing(2)` can be shortened to `mr: 2` when using the sx prop. Here are some other shortcuts available https://mui.com/system/the-sx-prop/

Positioning styles like `marginRight` should usually not be included in components that are expected to be reused like this `VerifiedBadge`.

**Review by QuaidBartolomei — CHANGES_REQUESTED** [review]

File: src/components/VerifiedBadge.js (hunk 1 above)
Comment (dadiorchen) [reply src/components/VerifiedBadge.js:11]: In short, I love the sx and now it's the most case (in my cases) that I compose CSS

Comment (VWRoli) [reply src/components/VerifiedBadge.js]: Thanks for the tip @QuaidBartolomei, good to know. I updated the code accordingly.

**Review by QuaidBartolomei — APPROVED** [review]
