### PR TITLE
fix: inconsistent height of cards

### LINKED ISSUE #1010: Featured Tree cards not same height
# Description
The height of the tree card is not the same if the text on 1 card is longer than the others, see screenshot below.
The long names do not occur on the dev environment by default (you could mock for easy testing)

Mobile|Desktop
:-:|:-:
image|image

## To reproduce
- run `npm run build-and-start`
- visit: http://localhost:3000/web-map-beta/demo/organizations/775

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by khalatevarun**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #1010

**Problem**: The cards were not of the same height since the height was not defined for the cards wrapped inside the `<Link/>` component.

**Solution**: Fixed by changing the `display` property of `Link` to `flex` and adding `flex:1` to `Card` component used in FeatureTreesSlider.

_NOTE_: the changes made in `Link.js` won't affect any areas as we are wrapping a single child component inside `<Link/> `component so changing the display property from `block` to `flex` won't make any ui changes.

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

### Desktop

|       Before        |       After        |
| :-----------------: | :----------------: |
| 192138443-058587ee-b61f-469d-9850-b8efbc9207bd | SCR-20220927-pbp|

### Mobile 
|       Before        |       After        |
| :-----------------: | :----------------: |
| 192138406-1de86b7d-de5f-48ed-968d-444dbf4baaaf | SCR-20220927-pcd|

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/components/Link.js [hunk 1]
```diff
@@ -22,7 +22,7 @@ const NextComposed = React.forwardRef((props, ref) => {
   return (
     <NextLink href={href} as={as}>
       <a
-        style={{ display: 'block' }}
+        style={{ display: 'flex' }}
```
Comment (RubenSmn) [inline src/components/Link.js:25]: Could you change this to `inline-flex`? We use this Link component in a lot of places so we do not want any layout changes caused by `flex`.

**Review by RubenSmn — CHANGES_REQUESTED** [review]

File: src/components/Link.js (hunk 1 above)
Comment (khalatevarun) [reply src/components/Link.js:25]: as mentioned in the NOTE section in the PR description, this should not affect any layout changes as we are wrapping only one component inside Link at a time

Comment (khalatevarun) [reply src/components/Link.js]: changes updated

**Review by RubenSmn — APPROVED** [review]
