### PR TITLE
fix: made images look better

### LINKED ISSUE #730: Restrain the image size on planter page
When the tree picture is big, the image size is inappropriate:

Image

comparing to the design:

Image

### PR DESCRIPTION
**Pull request by jeremydthomas**
# Description

[comment]: # 'made images look better on planter pages on various sizing'

Fixes #730 

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [ x] Bug fix (non-breaking change which fixes an issue)

## Screenshots
image
image

[comment]: # 'Please include screenshots of your changes if relevant.'

# How Has This Been Tested?

visual tests

# Checklist:

- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings

### CODE REVIEW

File: src/pages/planters/[planterid].js [hunk 1]
```diff
@@ -59,6 +59,13 @@ const useStyles = makeStyles()((theme) => ({
       marginBottom: theme.spacing(14),
     },
   },
+  profileImg: {
+    maxHeight: '764px',
+    borderRadius: '16px',
+    [theme.breakpoints.down('md')]: {
+      height: '332px',
+    },
+  },
```
Comment (dadiorchen) [inline src/pages/planters/[planterid].js:68]: @jeremydthomas we are abanding the class style to do the CSS, the recommended way is `sx`

So this case, you can put it on the img like this: (I'm not sure this is fully correct)

```
<Box 
  sx={{
      "& img": {
          maxHeight: [332, 764],
...
```

Comment (dadiorchen) [reply src/pages/planters/[planterid].js:68]: Another problem, looks the height is too big?

image


The figma is here: https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=4819%3A14477

Comment (dadiorchen) [reply src/pages/planters/[planterid].js:68]: Also, there is a mobile version for the same page, please check there to get the size

Comment (jeremydthomas) [reply src/pages/planters/[planterid].js:68]: @dadiorchen is the tree image that is there now, temporary? Because if I use those figma dimensions like that, it looks absolutely horrible

Comment (jeremydthomas) [reply src/pages/planters/[planterid].js:68]: > @jeremydthomas we are abanding the class style to do the CSS, the recommended way is `sx`
> 
> So this case, you can put it on the img like this: (I'm not sure this is fully correct)
> 
> ```
> <Box 
>   sx={{
>       "& img": {
>           maxHeight: [332, 764],
> ...
> ```

sounds good

Comment (jeremydthomas) [reply src/pages/planters/[planterid].js:68]: If i change the src to this

```
          <img src={`${router.basePath}${planterBackground}`} alt="profile" />
```

instead of this 
```
          <img src={backgroundPic} alt="profile" />
```

I get whats in the figma


image

Comment (dadiorchen) [reply src/pages/planters/[planterid].js:68]: @jeremydthomas take a look at this: https://stackoverflow.com/questions/3029422/how-do-i-auto-resize-an-image-to-fit-a-div-container

**Comment by dadiorchen** [comment]
@jeremydthomas great job!
