### PR TITLE
fix: issue #449 broken flags

### LINKED ISSUE #449: Broken flags
There are several flags broken, please fix them.

Screen Shot 2022-01-30 at 11 32 44 AM

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by VWRoli**
# Description

Created a function to fix the non-official country names. Placed it in the utils.js file. Other faulty country names should be added later on.

Fixes #449

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: src/models/utils.js [hunk 1]
```diff
@@ -79,11 +79,24 @@ function formatDateString(date) {
 const formatDates = (date) =>
   moment(date, 'ddd MMM DD YYYY HH:mm:ss').format('LL');
 
+// Fix country names so it get return the correct alpha2 code for the flags
+// todo other faulty country names should be added later
+const fixCountryNames = (countries) => countries.map((country) => {
+    if (country.name === 'Tanzania') {
+      return { ...country, name: 'Tanzania, United Republic of' };
```
Comment (dadiorchen) [inline src/models/utils.js:86]: @VWRoli Tanzania, United Republic of this is a standard country name? Interesting.

Comment (VWRoli) [reply src/models/utils.js:86]: I would assume it is to keep the alphabetical order of the country names.

Comment (dadiorchen) [reply src/models/utils.js:86]: make sense
