### PR TITLE
fix: zoom on mobile issue

### LINKED ISSUE #98: Can not pan the map in mobile device.
https://www.loom.com/share/1ae6fab6f524426d895dd15d6c8215fe

### PR DESCRIPTION
**Pull request by cpaule1811**
Resolves #98 

zoom-issue

Hi, 

The issue was due to the logo div's height not being static so the click event on zoom couldn't propagate because the div was blocking it.  

By setting the height of the logo div to 50px, it no longer prevents zoom click event from happening

https://user-images.githubusercontent.com/80873472/133403625-b7da83a7-b419-42ae-8149-0fcf741fbd6f.mp4

### CODE REVIEW

**Comment by dadiorchen** [comment]
@cpaule1811 awesome! this is a big problem for us, I didn't realize it is just because of this funny reason :D

File: src/components/Logo.js [hunk 1]
```diff
@@ -5,6 +5,7 @@ const useStyles = makeStyles(theme => ({
   logo: {
     userSelect: "none",
     position: "absolute",
+    height: 50,
```
Comment (dadiorchen) [inline src/components/Logo.js:8]: Yes, set the height is a good way to solve the problem, but I am thinking mayge the css property: user-event (I forgot the name) would be another approach, basically, with this property, the whole layer/div become un-interactable for the user.   (pointer-events ?)

Comment (dadiorchen) [reply src/components/Logo.js:8]: @mmayeda also I think if we remove the user interaction on the logo (for the mobile device), than we need to re-think the logo link, right?

Comment (cpaule1811) [reply src/components/Logo.js:8]: Yeah, so we can set pointerEvent: "none", however as you mentioned this would take away user interaction from the logo but it would fix the zoom controls issue if the logo interaction isn't important.

On a side note, setting height to 50 messes with the positioning on a large screen device, however if the height is closer to the actual logo container's height that won't be an issue. So 30 is probably a more appropriate height if we do choose to go down that route for this fix.

Comment (dadiorchen) [reply src/components/Logo.js:8]: I think for mobile device, we can remove the logo action? so using the material-ui breaking-point CSS property, we could set the pointerEvent on the mobile device?

Comment (dadiorchen) [reply src/components/Logo.js:8]: @mmayeda what do you think, I thought on the mobile device, it's not so necessary to click the logo, considering the screen is small.

Comment (mmayeda) [reply src/components/Logo.js:8]: I think we can set the pointer events to "none" on the parent div and add pointer events "auto" to the link element to keep the link functionality.  But I'm totally fine with removing the link functionality on the smaller screen too if it becomes a source of frustration by the way of users accidentally clicking it while trying to pan around on the smaller screen

Comment (dadiorchen) [reply src/components/Logo.js:8]: @mmayeda good idea, also, I agree, let's disable the logo action on the mobile device, @cpaule1811 can you make this change?

Comment (cpaule1811) [reply src/components/Logo.js:8]: No problem.

File: src/components/Logo.cy.js [hunk 2]
```diff
@@ -20,5 +20,6 @@ describe("Logo", () => {
     cy.get("a")
       .should("exist")
       .should("have.attr", "href", "https://greenstand.org/")
+      cy.viewport(800, 500)
```
Comment (mmayeda) [inline src/components/Logo.cy.js:23]: I don't think adjusting the viewport after making assertions buys us anything here.  Can we remove this line?

**Review by mmayeda — APPROVED** [review]
Thanks LGTM!

**Comment by dadiorchen** [comment]
Thank you @cpaule1811 for resolve this serious bug, a good improvement for us, I didn't expect it to be because of this reason, I thought it because some tricky bug with leaflet!

**Comment by dadiorchen** [comment]
I will release this version ASAP
