### PR TITLE
fix: handle api 404 error to display data properly

### LINKED ISSUE #1801: 404 error on /top page
steps to reproduce:
1. run `npm run dev` on v2 branch
2. click on the green "Let's Find a Tree" button on the home page
image
image

---
some hints:
- Please read this before you start: https://docs.greenstand.org/web-map/v2-web-map
- If you want to join the Slack community (some resources need the community member's permission), please leave your email address.

### PR DESCRIPTION
**Pull request by yunchipang**
# Description

Fixes #1801

⛔️ Cause: when populating static props (captures, countries, growers, organizations, wallets) in `top.js`, if any of the 5 items got a 404 upon API request, the page renders a 404 not found because the field was not properly populated.

🧩 Solution: consolidate all API request functions into `src/models/api.js`, including error handling. When an API request failed, the function returns an empty array.

📝 Note: For now, API requests to `captures` and `growers` return 404, so the below error persists, and the frontend is only displaying `countries`, `organizations`, and `wallets` (please refer to the screenshot in the next section). I believe the investigation should continue on [treetracker-query-api](https://github.com/Greenstand/treetracker-query-api) in terms of fetching captures and featured growers. I've checked `/captures` and `/growers/featured` endpoints, neither of them are working.

image

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots

|       Before        |       After        |
| :-----------------: | :----------------: |
| image | image |

# How Has This Been Tested?

- [x] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/models/api.js [hunk 1]
```diff
@@ -24,10 +24,10 @@ export async function getCaptures() {
     const res = await axios.get(url);
     const data = await res.data;
     log.warn('url:', url, 'took:', Date.now() - begin);
-    return data.captures;
+    return data.captures || [];
   } catch (err) {
-    log.error(err.message);
-    throw err;
+    log.error('Error in getCaptures:', err.message);
+    return [];
```
Comment (dadiorchen) [inline src/models/api.js:30]: @yunchipang why you disable the throwing here?

Comment (yunchipang) [reply src/models/api.js:30]: because if it throws an error, `getCaptures()` will not return anything, then `captures` in static props gets undefined, and the entire top page just shows 404.

for now, to inform the error i'm just logging it. would you like this to be handled in some other way? my purpose is to have some props display on the page even when some other props were not populated properly.

Comment (dadiorchen) [reply src/models/api.js:30]: I'm not sure, let's merge your code first, and we can continue, we can back to this if there are some problem. 

BTW, I also don't like the try-catch way to handle error, I prefer to use Promise function to do it:

promise
.then(goodHandler)
.catch(badHandler)

**Review by dadiorchen — APPROVED** [review]

**Comment by dadiorchen** [comment]
@yunchipang thanks for you contribution!
