### PR TITLE
fix: planter incorrect image rotation on organization page

### LINKED ISSUE #1306: Bug: planter images rotated incorrect on organization pages
# Description

The planter images are rotated incorrect on the organization pages

image

To reproduce
- visit: https://beta-map.treetracker.org/organizations/1333
- click on hired planters
- scroll through and see that many are rotated incorrect

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by salindae25**
# Description

 Planters' images are shown in the proper orientation on the Organization page.
 - Modified the `ProfileAvatar` Component; introduced `sx` props.
 - Change the `Avatar` component to the `ProfileAvatar` component and use the `image_rotation` property from the `planter` object.
 - Removed unused imports.

Fixes #1306

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

|       Before        |       After        |
|:-----------------: | :----------------: |
|208920633-8c7dd065-5e80-494c-9cbf-21a0c6ccd953 | image|

# Checklist:

- [x] I have performed a self-review of my own code

### CODE REVIEW

File: src/components/PlanterQuote.js [hunk 1]
```diff
@@ -75,15 +65,17 @@ function PlanterQuote(props) {
...
           src={photo}
+          rotation={planter.image_rotation}
           sx={{
             zIndex: '1',
             width: [90, 180],
             height: [90, 180],
             filter: 'drop-shadow(0px 10px 20px rgba(0, 0, 0, 0.25))',
             order: reverse ? 1 : 0,
             ml: reverse ? [26 / 8, 26 / 4] : 0,
+            mt: 'none',
```
Comment (RubenSmn) [inline src/components/PlanterQuote.js:78]: `'none'` is an invalid value for margin, it should be `0`

**Review by RubenSmn — CHANGES_REQUESTED** [review]

File: src/components/PlanterQuote.js (hunk 1 above)
Comment (salindae25) [reply src/components/PlanterQuote.js]: it is fixed.

**Review by RubenSmn — CHANGES_REQUESTED** [review]
There are some differences between the old and current style:
- `borderWidth`
- `borderStyle`
- `borderColor`
- `backgroundColor`

Are currently being applied to the `Avatar` in the `PlanterQuote` which they were not before.

**Comment by salindae25** [comment]
> There are some differences between the old and current style:
> 
> * `borderWidth`
> * `borderStyle`
> * `borderColor`
> * `backgroundColor`
> 
> Are currently being applied to the `Avatar` in the `PlanterQuote` which they were not before.

I left it like this because they were the default style of the `ProfileAvatar`. if it is not required for this i will remove them and only apply rotation transformation style

**Comment by RubenSmn** [comment]
@salindae25 yes they are the default style for our `ProfileAvatar` but not needed in this case :+1:

**Comment by RubenSmn** [comment]
Maybe to reduce the code in a lot of places where we don't use the background, border etc. we could introduce a new prop `noBackground` which will not apply the background and border styles?

**Review by RubenSmn — APPROVED** [review]
Thank you, great work!
