### PR TITLE
fix(ui): theme dark background timeline button

### LINKED ISSUE #895: Timeline button dark theme color incorrect
## Description
The background color of the timeline button is not the same as the drawer

Mobile Screenshot (same on desktop) 
image

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by tranquanghuy0801**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Update the background color of timeline button in dark theme

Fixes #895 

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

|       Before        |       After        |
| :-----------------: | :----------------: |
|  image  |  image |

# How Has This Been Tested?

- [x] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/components/Timeline.js [hunk 1]
```diff
@@ -130,7 +130,7 @@ function Timeline() {
           sx={{
             width: 22,
             '& path': {
-              fill: ({ palette }) => palette.primary.main,
+              fill: ({ palette }) => palette.primaryLight.main,
```
Comment (RubenSmn) [inline src/components/Timeline.js:133]: Primary light does not have a good contrast in the light mode, the `primary` works just fine. Could you change this back?

**Review by RubenSmn — CHANGES_REQUESTED** [review]

File: src/components/Timeline.js (hunk 1 above)
Comment (tranquanghuy0801) [reply src/components/Timeline.js]: Thanks for the feedback. I have updated in the latest commit.

**Review by RubenSmn — APPROVED** [review]
