### PR TITLE
fix(admin/theme): reset typography vals correctly

### LINKED ISSUE #1353: Theme editor global reset button not working for Typography
# Description

The global reset button on the Theme Editor does not work for the Typography values.

To reproduce

- visit: https://beta-map.treetracker.org/admin/theme
- change some Typography values
- click the global red reset button at the top

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by andrewsu31098**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #1353 
Added useEffect statement to reactively update TypographyInput when MUI theme was changed. 

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

|       Before        |       After        |
| :-----------------: | :----------------: |

[before](https://user-images.githubusercontent.com/48111116/213859084-516a2d71-c696-486c-b4be-3641e89959eb.PNG)
[after](https://user-images.githubusercontent.com/48111116/213859091-defe7d53-2905-4350-9d80-2a7ae98ad9ce.PNG)

# How Has This Been Tested?

- [x ] Cypress integration
- [ x] Cypress component tests

# Checklist:

- [x ] I have performed a self-review of my own code
- [ x] My changes generate no new warnings

### CODE REVIEW

File: src/components/playground/TypographyInput.js [hunk 1]
```diff
@@ -160,6 +160,10 @@ function FontFamily(props) {
     setPropByPath(path, userInput);
   };
 
+  useEffect(() => {
+    setValue(() => getPropByPath(path));
+  });
```
Comment (RubenSmn) [inline src/components/playground/TypographyInput.js:165]: We're missing a dependency array here

**Review by RubenSmn — CHANGES_REQUESTED** [review]

File: src/components/playground/TypographyInput.js (hunk 1 above)
Comment (andrewsu31098) [reply src/components/playground/TypographyInput.js]: Got it, added in theme as a dependency

**Review by RubenSmn — APPROVED** [review]
