### PR TITLE
 Initial view of this planter is wrong #1332 

### LINKED ISSUE #1332: Initial view of this planter is wrong
# Description

https://beta-map.treetracker.org/planters/6822 

Can not see any icons on the initial view

To reproduce

[comment]: # 'To reproduce'

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap).
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/26

### PR DESCRIPTION
**Pull request by SuokN**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #1332  Initial view of planters, organizations, wallets are loading correctly with new version of treetracker-web-map-core.

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

# How Has This Been Tested?

- [x] Cypress integration
- [x] Cypress component tests

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/components/InformationCard1.js [hunk 1]
```diff
@@ -2,10 +2,10 @@ import { Card, Box, Button, Avatar, Typography } from '@mui/material';
 import { useTheme } from '@mui/material/styles';
 import * as d3 from 'd3';
 import log from 'loglevel';
+import Logo from 'images/greenstand_logo.svg';
```
Comment (dadiorchen) [inline src/components/InformationCard1.js:5]: @SuokN you are bringing irrelevant code into this PR, principlely, the smaller a PR is, the better. My preferred way to work with git/github is checkout the newest code ever time:
```
git fetch --all && git checkout greenstand/beta && git checkout -b issuetofix
```
