### PR TITLE
fix: broken layout for longer names

### LINKED ISSUE #992: Planter page: broken layout
https://prod-k8s.treetracker.org/web-map-beta/demo/planters/3939?keyword=undefined

The species component get distort because of long text

Image

### PR DESCRIPTION
**Pull request by khalatevarun**
# Description

[comment]: # 'Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.'

Fixes #992 

**Problem**: The layout for card was broken for longer names.

**Solution**: Add wordWrap and fixed width property to limit the name up to particular length and shift the rest to next line.

_NOTE: increased padding for inner card content, the height of the card is slightly increased._

## Type of change

[comment]: # 'Please delete options that are not relevant.'

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

[comment]: # 'Please include screenshots of your changes if relevant.'

|       Before        |       After        |
| :-----------------: | :----------------: |
| 191858432-41a0f344-c4d4-4c7c-8ba6-3a7e84c47e54|SCR-20220927-way|

# How Has This Been Tested?

- [ ] Cypress integration
- [ ] Cypress component tests
- [ ] Jest unit tests

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/components/TreeSpeciesCard.js [hunk 1]
```diff
@@ -70,7 +77,7 @@ function TreeSpeciesCard(props) {
           sx={{
             background: (t) => t.palette.background.paperDark,
             color: (t) => t.palette.text.primaryReverse,
-            padding: (t) => [t.spacing(3, 5), t.spacing(6, 8)],
+            padding: (t) => [t.spacing(4.5, 6.5), t.spacing(6, 8)],
```
Comment (RubenSmn) [inline src/components/TreeSpeciesCard.js:80]: Personally I do not see the need of a padding increase, what is your opinion @jeremydthomas ?

Comment (RubenSmn) [reply src/components/TreeSpeciesCard.js:80]: I see the issue now, when wordwrapping the text can become a little close to the border

File: src/components/TreeSpeciesCard.js [hunk 2]
```diff
@@ -32,7 +32,14 @@ function TreeSpeciesCard(props) {
         justifyContent="space-between"
         alignItems="center"
       >
-        <Grid item ml={6}>
+        <Grid
+          item
+          ml={6}
+          sx={{
```
Comment (RubenSmn) [inline src/components/TreeSpeciesCard.js:38]: @khalatevarun could you add some vertical padding here and undo the change other (count element) padding

**Review by RubenSmn — CHANGES_REQUESTED** [review]

File: src/components/TreeSpeciesCard.js (hunk 1 above)
Comment (jeremydthomas) [reply src/components/TreeSpeciesCard.js:80]: I haven't actually looked at it more than a glance to be honest. What I did see seemed better than what I did. I was working on something else tonight, also about to go home here in a bit.

File: src/components/TreeSpeciesCard.js (hunk 2 above)
Comment (khalatevarun) [reply src/components/TreeSpeciesCard.js:38]: I tried doing the same initally but as a consequence of that, there is additional white space created on top and bottom of count element.
Please refer to image attached. 
SCR-20220928-s54

Comment (khalatevarun) [reply src/components/TreeSpeciesCard.js:38]: I think adding padding for the count element is would be better as it would result only slight increase in the list height.

Comment (RubenSmn) [reply src/components/TreeSpeciesCard.js:38]: We could fix this by adding `align-self: stretch` to the count box.

Comment (RubenSmn) [reply src/components/TreeSpeciesCard.js:38]: If we don't add the padding to the description side of the box the spacing will not look the same for all cards
image

Comment (khalatevarun) [reply src/components/TreeSpeciesCard.js:38]: makes sense, but it would result in cards of different heights since some name will take 2 lines and adding vertical padding will further increase vertical height thus resulting in inconsistency?

Can surely make changes suggested by you if the above mentioned concern is not a big deal. 
Let me know if I should undo my changes and add vertical padding.

Comment (RubenSmn) [reply src/components/TreeSpeciesCard.js:38]: I think its fine if height increases when we have more than 1 line.

Comment (khalatevarun) [reply src/components/TreeSpeciesCard.js:38]: okay, will update changes

**Comment by RubenSmn** [comment]
@dadiorchen this was not ready yet, we are still having some spacing issues if the specie name is really long or if the device width is small

image

**Comment by dadiorchen** [comment]
Oh, what's should I do now? revert?

**Comment by khalatevarun** [comment]
> 

I have created another PR with updated changes.
